### ISSUE TITLE
Reduce bandwidth required by issue updates

### ISSUE THREAD

**Issue by gbiggs** [open-rmf/rmf_internal_msgs#19]
### Description

Each query update currently includes a copy of the relevant query and the query ID. This information is redundant and wastes bandwidth, possibly significantly for complex queries. Remove these from the message without impacting the existing behaviour and robustness.

See [this comment](https://github.com/open-rmf/rmf_internal_msgs/pull/16#discussion_r658518030) for more information and context.

### Implementation considerations

The query is included to improve the robustness of the mirrors to errors in the schedule node. An alternative approach needs to be provided for mirrors to verify they are receiving updates for their query.

**Comment by mxgrey** [comment]
This issue should be closed by https://github.com/open-rmf/rmf_ros2/pull/86
